Task 1: Array Creation and Data Types

*Objective*: Practice initializing arrays and inspecting their properties.

1. Create the following arrays:
   - A 3x3 identity matrix.
   - A 1D array of 20 linearly spaced values between 5 and 50.
   - A 5x5 array filled with random floats from a normal distribution (mean = 0, std = 1).
2. Print the dtype, shape, and ndim of each array.

3. Convert the 5x5 array to integer type using .astype() and explain any change in values.

In [36]:
import numpy as np
identity = np.identity(3)
print(identity)
print(f"identity's shape is{identity.shape}, its type is {identity.dtype} and its dimensions are {identity.ndim}")
array_1D = np.arange(5,50,2.25)
print(array_1D)
print(f"array_1D's shape is{array_1D.shape}, its type is {array_1D.dtype} and its dimensions are {array_1D.ndim}")
samples = np.random.standard_normal(size=(5,5))
print(samples)
int_array = samples.astype(np.int64)
print(int_array)
print(f"samples 's shape is{samples .shape}, its type is {samples .dtype} and its dimensions are {samples .ndim}")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
identity's shape is(3, 3), its type is float64 and its dimensions are 2
[ 5.    7.25  9.5  11.75 14.   16.25 18.5  20.75 23.   25.25 27.5  29.75
 32.   34.25 36.5  38.75 41.   43.25 45.5  47.75]
array_1D's shape is(20,), its type is float64 and its dimensions are 1
[[-1.13330086  1.22392777  0.13635237 -1.02266828 -0.16594571]
 [ 1.79410494 -0.06504024 -0.33174204 -0.25030622  1.94868787]
 [ 0.19514566 -0.86448734  0.88594428 -1.4797066   0.18347255]
 [ 0.04681809 -0.09125535  1.11331286 -0.0223134   0.7134927 ]
 [-0.90362803 -0.86871347 -0.63400197 -0.93979482 -0.39433011]]
[[-1  1  0 -1  0]
 [ 1  0  0  0  1]
 [ 0  0  0 -1  0]
 [ 0  0  1  0  0]
 [ 0  0  0  0  0]]
samples 's shape is(5, 5), its type is float64 and its dimensions are 2


 Task 2: Vectorization and Arithmetic Operations

*Objective*: Apply element-wise operations and use vectorized computation.

1. Create an array a of 10 integers from 1 to 10.

2. Create a new array b where each element is:
   - a_i * 2 if a_i is even
   - a_i + 5 if a_i is odd

   Use np.where() to implement this logic.

3. Compute and print:
   - Element-wise multiplication of a and b
   - Boolean mask for values in b greater than 15
   - The sum and standard deviation of array b

In [35]:
import numpy as np
a = np.arange(1,11,1)
print(a)
b = np.where(a%2 == 0, a*2, a+5)
print(b)
multiply_array = a * b
print(f"Element-wise multiplication of a and b is {multiply_array}")
b > 15
sum = np.sum(b)
print(f"Sum of array b is {sum}")
deviation = np.std(b)
print(f"Standard deviation of array b is {deviation}")


[ 1  2  3  4  5  6  7  8  9 10]
[ 6  4  8  8 10 12 12 16 14 20]
Element-wise multiplication of a and b is [  6   8  24  32  50  72  84 128 126 200]
sum of array b is 110
standard deviation of array b is 4.58257569495584


Task 3: Indexing and Slicing

*Objective*: Master subsetting arrays with slice notation and boolean masks.

Given a 6x6 matrix of integers from 1 to 36:

1. Reshape it from a 1D range to 6x6.

2. Extract:
   - The 3rd row.
   - The last column.
   - All elements greater than 20 (use boolean indexing).
   - The submatrix formed by rows 2 to 4 and columns 2 to 5.

3. Modify the matrix: Set all even numbers to 0 using boolean indexing.

In [54]:
import numpy as np
array = np.arange(1,37).reshape(6,6)
print(array)
print(array[2:3,:])
print(array[:,5:])
array[array>20]
print(array[2:4,2:5])
array[array%2==0 ] = 0
array

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[13 14 15 16 17 18]]
[[ 6]
 [12]
 [18]
 [24]
 [30]
 [36]]
[[15 16 17]
 [21 22 23]]


array([[ 1,  0,  3,  0,  5,  0],
       [ 7,  0,  9,  0, 11,  0],
       [13,  0, 15,  0, 17,  0],
       [19,  0, 21,  0, 23,  0],
       [25,  0, 27,  0, 29,  0],
       [31,  0, 33,  0, 35,  0]])

Task 4: Fancy Indexing and Transposition

*Objective*: Use index arrays for advanced data selection and understand axis operations.

1. Create a 4x4 array of random integers from 10 to 99.

2. Using fancy indexing, extract the diagonal elements using index arrays.

3. Transpose the matrix and print both original and transposed matrices.

4. Use swapaxes() to switch axes of a 3D array of shape (2, 3, 4) and explain the result.

In [88]:
import numpy as np
# creating a custom generator object to craete random numbers
rng = np.random.default_rng(seed =1234)
array = rng.integers(10,99,size=(4,4))
#print(array)
diagonal_elements = array[[0,1,2,3],[0,1,2,3]]
print(array.T)
print(array)
array2 = rng.integers(10,99,size=(2,3,4))
# print(array2)
array2.swapaxes(0,1)
array2.swapaxes(1,2)
array2.swapaxes(2,0)
# Here swapaxes takes the pair of axes numbers and rearrange the data around the given axes

[[97 25 22 80]
 [96 92 38 31]
 [97 19 57 79]
 [43 33 20 38]]
[[97 96 97 43]
 [25 92 19 33]
 [22 38 57 20]
 [80 31 79 38]]


array([[[80, 56],
        [59, 14],
        [89, 87]],

       [[95, 70],
        [49, 75],
        [86, 25]],

       [[95, 95],
        [32, 75],
        [67, 80]],

       [[33, 68],
        [64, 29],
        [86, 87]]])

 Task 5: Universal Functions and Broadcasting

*Objective*: Apply NumPy ufuncs and broadcasting logic.

1. Create an array of 10 values drawn from a uniform distribution between 0 and 1.

2. Compute:
   - The square root using np.sqrt
   - The exponential using np.exp
   - Element-wise max of this array and a constant 0.5 using np.maximum

3. Create a 3x5 matrix and subtract the column-wise mean using broadcasting.

In [112]:
import numpy as np
rng = np.random.default_rng(seed =1234)
array = rng.uniform(low = 0, high = 10,size=10)
#print(array)
print(f"Square root array is {np.sqrt(array)}")
print(f"Exponential array is {np.exp(array)}")
print(f"Element wise max of an array is {np.maximum(array,0.5)}")
array2 = rng.standard_normal(size=(3,5))
#print(array2)
columnwise_mean = array2.mean(axis = 0)
#print(columnwise_mean)
subtracted_array = np.subtract(columnwise_mean,array2)
print(f"Subtracted array is{subtracted_array}")


Square root array is [3.12521962 1.94986085 3.03849672 1.61769102 1.7863288  1.0866979
 1.55488358 1.78475188 3.10496255 1.62372967]
Exponential array is [1.74483029e+04 4.47887661e+01 1.02236847e+04 1.36935407e+01
 2.43120128e+01 3.25734462e+00 1.12196077e+01 2.41754895e+01
 1.53795264e+04 1.39642158e+01]
Element wise max of an array is [9.76699767 3.80195735 9.23246234 2.61692424 3.19097058 1.18091233
 2.41766293 3.18533929 9.64079245 2.63649804]
Subtracted array is[[-0.28863535 -0.48186975  1.54837391 -0.55875435  0.74146701]
 [ 1.35805995  0.40715525 -1.0451956  -0.55939531  0.47848909]
 [-1.0694246   0.0747145  -0.50317831  1.11814966 -1.2199561 ]]


Task 6: Random Sampling and Simulation

*Objective*: Use np.random for simulations.

1. Simulate 1000 random walks each of 100 steps:
   - Each step is +1 or -1 with equal probability.
   - Represent all walks in a 2D array: shape (1000, 100).

2. Compute:
   - Final position of each walk.
   - Number of walks that ended beyond +10 or below -10.

3. Visualize a few sample walks (optional using matplotlib).

In [127]:
import numpy as np
rng = np.random.default_rng(seed = 1234)
nwalks =1000
nsteps = 100
draws = rng.integers(0,2,size =(nwalks,nsteps))
steps = np.where(draws>0, 1,-1)
walks = steps.cumsum(axis = 1)
print(walks)
final_position = steps.sum(axis = 1)
beyond_10 = (np.abs(walks) >10).any(axis =1)
beyond_10.sum()


[[  1   2   3 ...   8   9   8]
 [  1   2   1 ...  -4  -5  -6]
 [  1   0  -1 ...   0   1   0]
 ...
 [ -1   0  -1 ... -16 -17 -16]
 [  1   0   1 ...  -4  -5  -6]
 [ -1   0  -1 ...   6   7   8]]


555

Task 7: Matrix Algebra

*Objective*: Use np.dot, @, and np.linalg methods.

1. Generate two 3x3 matrices A and B with random integers between 1 and 10.

2. Compute:
   - The matrix product using np.dot() and the @ operator.
   - The inverse of A using np.linalg.inv() (handle error if not invertible).
   - The determinant of A.

3. Solve the linear system Ax = b where b = [1, 2, 3].

In [145]:
import numpy as np
from numpy.linalg import inv ,det ,solve
rng = np.random.default_rng(seed = 1234)
A = rng.integers(1,10,size=(3,3))
print(A)
B = rng.integers(1,10,size=(3,3))
dot_product = np.dot(A,B)
operator_product = A @ B
inverse_matrix = inv(A)
print(inverse_matrix )
determinant_matrix = det(A)
print(determinant_matrix)
x = solve(A ,b = [1,2,3])
print(x)



[[9 9 9]
 [4 2 9]
 [1 3 2]]
[[ 0.21296296 -0.08333333 -0.58333333]
 [-0.00925926 -0.08333333  0.41666667]
 [-0.09259259  0.16666667  0.16666667]]
-108.00000000000003
[-1.7037037   1.07407407  0.74074074]
[[9 9 9]
 [4 2 9]
 [1 3 2]]


Task 8: File I/O with NumPy

*Objective*: Save and load arrays from disk.

1. Save array a and array b from Task 2 into a .npz file.

2. Load the .npz file and verify the contents.

In [151]:
import numpy as np
np.savez("a.npz", a = np.arange(1,11,1), b = np.where(a%2 == 0, a*2, a+5))
arch = np.load("a.npz")
arch["b"]


array([ 6,  4,  8,  8, 10, 12, 12, 16, 14, 20])

Bonus Task: Memory Efficiency

*Objective*: Understand view vs. copy in slicing.

1. Create a 1D array of numbers from 0 to 99.

2. Slice out elements from index 20 to 40. Modify this slice and check if the original array reflects the change.

3. Use .copy() to create an independent array and repeat the test.

In [155]:
import numpy as np
array = np.arange(0,99)
array[20:40]
print(array)
array2 = array.copy()
array2[0] = 44
print(array2[0:2])





[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[44  1]
